name: Pull request

on:
  pull_request:
    branches: ['main']

jobs:
  # Build job
  builddev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled
      - name: Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Lint
        run: |
          bun run lint
      - name: Build
        run: |
          bun run build
      - name: Test
        run: |
          bun run test
